### ISSUE TITLE
单独运行HTMLTestRunner，报错

### ISSUE THREAD

**Issue by sky1984** [yingoja/DemoUI#3]
self.passrate = str("%.2f%%" % (float(result.success_count) / float(result.success_count + result.failure_count + result.error_count) * 100))

**Comment by sky1984** [comment]
"D:\Program Files\Python37\python.exe" "D:/Program Files/Python37/Projects/DemoUI-master/package/HTMLTestRunner.py"
Traceback (most recent call last):
  File "D:/Program Files/Python37/Projects/DemoUI-master/package/HTMLTestRunner.py", line 961, in <module>
    main(module=None)
  File "D:\Program Files\Python37\lib\unittest\main.py", line 101, in __init__
    self.runTests()
  File "D:/Program Files/Python37/Projects/DemoUI-master/package/HTMLTestRunner.py", line 952, in runTests
    unittest.TestProgram.runTests(self)
  File "D:\Program Files\Python37\lib\unittest\main.py", line 271, in runTests
    self.result = testRunner.run(self.test)
  File "D:/Program Files/Python37/Projects/DemoUI-master/package/HTMLTestRunner.py", line 746, in run
    self.generateReport(test, result)
  File "D:/Program Files/Python37/Projects/DemoUI-master/package/HTMLTestRunner.py", line 796, in generateReport
    report_attrs = self.getReportAttributes(result)
  File "D:/Program Files/Python37/Projects/DemoUI-master/package/HTMLTestRunner.py", line 784, in getReportAttributes
    self.passrate = str("%.2f%%" % (float(result.success_count) / float(result.success_count + result.failure_count + result.error_count) * 100))
ZeroDivisionError: float division by zero
